# Generated by Django 5.1.3 on 2024-11-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medium', '0002_alter_post_options_alter_post_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='edit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Post Title')),
                ('image', models.ImageField(upload_to='static/', verbose_name='Post Image')),
                ('content', models.TextField(verbose_name='Post Content')),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='Date Posted')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ('-date_posted',),
            },
        ),
    ]
