# Generated by Django 5.1.3 on 2024-11-20 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medium', '0003_edit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='edit',
        ),
    ]
