# Generated by Django 5.1.3 on 2024-11-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default.jpg', max_length=255, upload_to='static/profile'),
        ),
    ]
