# Generated by Django 5.1.3 on 2024-12-04 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0008_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
    ]
